name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read-write

jobs:
  main:
    name: 🔁 Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint test build

  release:
    name: 🏷️ Release
    runs-on: ubuntu-latest
    needs: [main]
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: release
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print latest commit
        run: echo ${{ github.sha }}

      - name: Cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - Configure Git
        run: |
            git config --global user.email ${{ secrets.USER_EMAIL }}
            git config --global user.name ${{ secrets.USERNAME }}

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx release --skip-publish
