name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  main:
    name: 🔁 Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - name: Run affected commands
        run: npx nx affected -t lint test build e2e

  release:
    name: 🏷️ Release
    runs-on: ubuntu-latest
    needs: [main]
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: release
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx release --skip-publish --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ⛴️ Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 📦 Build wjt-service
        run: npx nx build wjt

      - name: 🔨 Build WJT Docker Image
        run: docker buildx build --platform linux/amd64 -f apps/wjt/Dockerfile -t wijohnst/wjt .

      - name: 📌 Push WJT Docker Image
        run: docker push wijohnst/wjt:latest

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ secrets.SSH_PW}} | sudo -S docker pull wijohnst/wjt:latest
            echo ${{ secrets.SSH_PW}} | sudo -S docker stop wjt
            echo ${{ secrets.SSH_PW}} | sudo -S docker rm wjt
            echo ${{ secrets.SSH_PW}} | sudo -S docker run -d -p 4200:4200 --name wjt wijohnst/wjt:latest
